# Generated by Django 2.1.7 on 2019-03-19 18:35

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File

def load_posts(apps, schema_editor):
    """Read CSV file of data and add it to the post website"""
    Post = apps.get_model('core', 'Post')
    Author = apps.get_model('core', 'Author')
    # revisting migrating comments once other things are functional
    # Comment = apps.get_model()

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'posts.csv')

    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:
            post_author, _ = Author.objects.get_or_create(name=row['author'])
            
            post = Post(
                title = row['title'],
                content = row['content'],
                author = post_author,
                url = row['url'],
            )
            post.save()






class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_posts)
    ]
