# Generated by Django 2.1.7 on 2019-03-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190319_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date_added']},
        ),
    ]
