# Generated by Django 2.1.7 on 2019-03-25 13:17
from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User
import os.path
import csv

def load_posts(apps, schema_editor):
    """Read CSV file of data and add it to the post website"""
    Post = apps.get_model('core', 'Post')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'posts.csv')

    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:

            users_who_favorited = []
            if row['users_who_favorited']:
                for user_string in row['users_who_favorited'].split('/'):
                    favorite_user, _ = User.objects.get_or_create(username=user_string)
                    users_who_favorited.append(favorite_user)

            post_author, created = User.objects.get_or_create(username=row['author'])
            print(post_author,'pk',post_author.pk, created)

            post = post_author.posts.create(                
                title = row['title'],
                content = row['content'],                
                url = row['url'])

            # post = Post(
            #     title = row['title'],
            #     content = row['content'],
            #     author = post_author,
            #     url = row['url'],
            # )
            # post.save()

            if users_who_favorited:
                for user in users_who_favorited:
                    post.favorited_by.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190323_2031'),
    ]

    operations = [migrations.RunPython(load_posts)
    ]
